quotes = ["The universe is a marvel of creation, a testament to the incredible power and beauty of God's design.",
          "The truest form of knowledge is acknowledging what you don't know.",
          "The search for meaning is a journey, not a destination.",
          "The most important questions in life have no answers, only perspectives.",
          "The only true power we possess is the power of choice.",
          "In a world of uncertainty, the only constant is change.",
          "We are the sum of our experiences, but we are not defined by them.",
          "The only limit to our potential is the limit we place on ourselves.",
          "The key to happiness is not in what we have, but in how we appreciate what we have.",
          "The value of life is not in its length, but in its depth.",
          "To know thyself is the beginning of all wisdom.",
          "The truest form of courage is the courage to be vulnerable.",
          "The pursuit of knowledge is the pursuit of understanding.",
          "The beauty of life is found in the moments when we allow ourselves to be fully present.",
          "The only way to find peace is to accept the present moment as it is.",
          "We are not human beings having a spiritual experience, but spiritual beings having a human experience.",
          "The true measure of success is not in what we achieve, but in who we become.",
          "The most valuable things in life are not things at all, but experiences and relationships.",
          "We are all interconnected, and our actions have ripple effects beyond what we can comprehend.",
          "The greatest obstacles we face are often the ones we create ourselves.",
          "The pursuit of happiness is a never-ending journey, but the pursuit itself is what gives life meaning.",
          "The only way to change the world is to change ourselves.",
          "Our perception of reality is limited by our beliefs and biases.",
          "The only true failure in life is the failure to try.",
          "The greatest gift we can give to others is the gift of understanding.",
          "The only true liberation is the liberation of the mind.",
          "The only way to experience true freedom is to let go of our attachments and expectations.",
          "The universe starts from you, and is as big, as your ability to perceive the reality.",
          "Out of an infinity of possibilities, it happens that we exist, and it's a pleasure to share this precious moment with you!",
          "Every moment you lose, is a moment you will not be able to get back. So live your life at full intensity.",
          "Your ability to perceive reality determines the boundaries of the universe, so never stop exploring and expanding your understanding.",
          "Home is where your heart and your puppy are, and it's a wonderful feeling to have such unconditional love in your life.",
          "Each and every one of us is a unique and special creation of God, and we all have something incredible to offer this world.",
          "There is nothing more special than the feeling of being at home, surrounded by the people and things you love.",
          "The universe is full of incredible and magical surprises, just waiting for us to discover them.",
          "Your unique talents and abilities are a gift to the world, and nothing is impossible when you believe in yourself.",
          ]